### ISSUE TITLE
The application did not respond

### ISSUE THREAD

**Issue by the4ndy** [great-illuminary/lorcana-discord#1]
Is this discord app/bot still usable? I tried adding it to my discord server but all functions appear to be broken. I cannot look up a card, it finds no results for Set, ID, or Lang.

![image](https://github.com/great-illuminary/lorcana-discord/assets/3416319/c83c1c78-89c7-4a72-b872-d575159b3949)

please advise

**Comment by codlab** [comment]
It’s currently in maintenance, it should be back in an hour or so

**Comment by codlab** [comment]
It’s normally ok now - switching back to updating all the data 😜
